"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dtool-lookup-openapi-client
from dtool-lookup-openapi-client.model.pagination_metadata import PaginationMetadata


class TestPaginationMetadata(unittest.TestCase):
    """PaginationMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginationMetadata(self):
        """Test PaginationMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginationMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
