"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dtool-lookup-openapi-client
from dtool-lookup-openapi-client.model.dependency_keys import DependencyKeys


class TestDependencyKeys(unittest.TestCase):
    """DependencyKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDependencyKeys(self):
        """Test DependencyKeys"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DependencyKeys()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
