"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dtool-lookup-openapi-client
from dtool-lookup-openapi-client.model.uri import Uri


class TestUri(unittest.TestCase):
    """Uri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUri(self):
        """Test Uri"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Uri()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
